version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 app:
  build: regov-reg-portal # specify the directory of the Dockerfile
  ports:
  - "3000:3000" # specify port mapping
 
 backend:
  build: regov-backend # specify the directory of the Dockerfile
  ports:
  - "8080:8080" #specify ports mapping
  links:
  - database # link this service to the database service
 
 database:
  image: mongo # specify image to build container from
  ports:
  - "27017:27017" # specify port forwarding